### ISSUE TITLE
FsCheck tests won't run:

### ISSUE THREAD

**Issue by DavidTheBugWriter** [fsharp/FAKE#1131]
This basic FsCheck fails:
```
open NUnit.Framework
open FsCheck.NUnit
[< Property>]
let ``Reverse of reverse of a list is the original list ``(xs:list<int>) =
                    List.rev(List.rev xs) = xs

```
I get this error:
> Tests Not Run:
> 1) NotRunnable : secondproject.Tests.Reverse of reverse of a list is the original list 
> Test method has non-void return type, but no result is expected

My build.fsx file has this as a test test runner:

```
Target "RunTests" (fun _ ->
    !! testAssemblies

    |> NUnit (fun p ->
        { p with
            DisableShadowCopy = true
            Domain = NUnitDomainModel.NoDomainModel 
            TimeOut = TimeSpan.FromMinutes 20.
            OutputFile = "TestResults.xml" })
)
```

**Comment by mFingers** [comment]
I haven't used fscheck, so this is a guess.  Your test method is returning a bool (because the result of the last expression in a function is the return type), and based on the error message, it should return void (or "unit" in F#).

I'm guessing that if you do your assertion using the unit testing library, that it will test your assertion, and return void.

**Comment by dsyme** [comment]
Closing old inactive discussion - this looks unrelated to FAKE
