### ISSUE TITLE
paket.dependencies broken with latest paket.exe

### ISSUE THREAD

**Issue by sillyotter** [fsharp/FAKE#1289]
### Description

While building FAKE today to test a fix to Fake.Deploy, I found that paket will fail now if it finds duplicate package references in the paket.dependencies file.  I actually found this out today in several of my own paket based projects as well which worked last week, so it must be a new change to paket.  This projects paket.dependencies has a duplicate reference to xunit.runners.  In fact, i guess your CI builds are failing for this reason as well.  (My fake.deploy PR is failing for this reason)
### Repro steps

Just do a build, it fails really quickly now if you have the latest paket installed.  So maybe clean the .paket folder to force it to get the latest one.
### Fix

Deleting either of the lines fixes it.  I didn't want to include that in my recent PR, and it seemed a bit trivial to justify making a whole new PR for it.  Also, one includes a version constraint, one doesn't, and I don't know which is the right one.

**Comment by forki** [comment]
Yes we changed that in paket for (at least I hope) good reasons.
Unfortunately now we need to update downstream projects.

**Comment by forki** [comment]
That said: I should have added the change in a different place so that it
doesn't affect restore. Can you please open an issue in paket for that.
Stupid me.
On Jun 29, 2016 9:30 PM, "Steffen Forkmann" <sforkmann@gmail.com> wrote:

Yes we changed that in paket for (at least I hope) good reasons.
Unfortunately now we need to update downstream projects.

**Comment by smoothdeveloper** [comment]
I think we should close this now, the `paket.dependencies` file has been fixed.
