### ISSUE TITLE
Docs: a function index would be nice

### ISSUE THREAD

**Issue by rmunn** [fsharp/FAKE#1485]
### Description

The FAKE API documentation is hard to use: specifically, there's no one place to find out all the available functions. I can click through a bunch of namespaces until I find what I'm looking for, but it's not always obvious at all which namespace contains what.

### Repro steps

Here's a good example. I just tried to look for the `</>` operator, because I had to refresh my memory whether `</>` or `@@` was the operator that strips leading slashes from the second part of the path. (It's `@@`, but I couldn't remember that). Here's the process I went through:

1. Click on http://fsharp.github.io/FAKE/apidocs/index.html
1. Hmm, which namespace is that in?
1. Probably FileHelper. Or FileSystem. Or FileSystemHelper. Let's open all three of those in new tabs.
1. Nope, none of those. Maybe FileUtils?
1. Nope. Let's see, is there a DirectoryHelper? No. Maybe a PathHelper? No.
1. Wait, I remember I was looking for it last month, and it was in a namespace I didn't expect. Hmm, the MsBuildHelper namespace, maybe?
1. No, not that one. Oh look, ProcessHelper, I bet that's where it was.
1. No, not there either. I dunno, let's grep the FAKE source code for the string `</>`.
1. Ohhhh, it was in EnvironmentHelper. Let me make a mental note of that for next time, but I'll probably forget again.

### Expected behavior

I'd like to have an index of all FAKE functions available, in *all* namespaces. Each entry would look something like this (vague ASCII art, do *not* take this as the final design that I'd like to see):

```plain
</> path1 path2      Description of </>
From Fake.EnvironmentHelper (auto-opened when you put "open Fake" in your build script)

@@ path1 path2       Description of @@
From Fake.EnvironmentHelper (auto-opened when you put "open Fake" in your build script)

.
.
.

Pack setParams       Description of Pack
From Fake.Paket (NOT auto-opened: need to put "open Fake.Paket" in your build script)
```

The sort order I'd prefer to see would be to have ASCII letters sorted NOT case-sensitive, so that (for example) `getBuildParam` comes before `GetDependenciesForReferencesFile` which comes before `getDrivesInfo`. Also if Fake defines any operators that start with the `|` (vertical pipe) character, I'd like to see them sorted *before* the ASCII letters, so that all operators are clustered together in the index. This would take a custom sorter, since `|` is U+007C, coming after the lowercase letters if you sort in code point order.

Finally, I'd like the index to have 27 links at the top (and maybe at the bottom as well) for ease of navigation: one link titled `!@#` (or whatever) that links to the names that start with non-letter characters, and then the letters A through Z as links to that section of the index. Each section would have a "Back to top" link, too.

### Actual behavior

I had to grep the source code to find where the `</>` operator was defined. Any time you end up searching the source code, it's because the documentation was lacking in some way. Sometimes that's all right, but in this case, this was a very commonly-needed operator that I couldn't find, so we should improve the documentation so that it's easier to find. A function index is the best idea I have for that improvement.

### Known workarounds

If you forget which namespace a particular operator or function is from, a long search or a grep through FAKE's source code are your only options at the moment.

**Comment by theprash** [comment]
For operators, which are hard to search for, I would go with this approach which works for me in Visual Studio: Type `(@@)` in the script and then hover over it to get the doc string and fully qualified name. However, these particular docs aren't useful for distinguishing the trimming behaviour of the two operators (ahem, that's partly my fault actually).

But I agree it's generally a problem. My general approach to documentation for almost everything is to use a search engine. So I might google for something like "fake msbuild", and this generally works for me. Perhaps a quick improvement might be to have a search box in the API docs that takes the term `msbuild` and turns it into the Google search: `msbuild site:http://fsharp.github.io/FAKE/apidocs`.

**Comment by matthid** [comment]
@cloudRoutine Maybe something for FSF. Should we track that there?

**Comment by cloudRoutine** [comment]
A search by function name & search by type signature query box has long been on the list of features I want to add to the api pages via fable. You can add an issue for it if you want, but I don't need it.

**Comment by rmunn** [comment]
Those would also be great features to have, and would complement an index nicely. If a search feature was available, it would cover my usual problem with the FAKE documentation, which is not knowing where to find a specific function. An index would still provide something valuable that a search function couldn't, though, which is discoverability. Someone new to FAKE, or any library for that matter, could browse through the index and perhaps discover some useful functions that he/she didn't know about. So I'll keep this feature request open even if a search feature gets added before an index.

**Comment by pr-yemibedu** [comment]
Hello,
 What would be helpful if searching is not possible is a set of generated Appendix pages (@rmunn ). Each would be for all public values in a namespace / module:
 - functions
 - types
 - record fields

 So these would just allow built in browser incremental searching instead of reinventing that wheel.

 I had this same ordeal working between what is Nunit3 (what I wanted) and what was Nunit2 and what was common. But then Dotcover uses that internally and so github repo searches were painful to get the right incantation of my spell.

## Function Appendix
Function | Module/Namespace
--- | ---
[buildDotCoverArgs](http://fake.build/apidocs/fake-dotcover.html) | [Fake.DotCover](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/DotCover.fs)

## Type Appendix
Type | Module/Namespace
--- | ---
[DotCoverParams](http://fake.build/apidocs/fake-dotcover-dotcoverparams.html) | [Fake.DotCover](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/DotCover.fs)
[NUnitParams](http://fake.build/apidocs/fake-nunitcommon-nunitparams.html) | [Fake.NUnitCommon](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/UnitTest/NUnit/Common.fs)

## Field Appendix
Field | Type | Module/Namespace
--- | --- | --
[ErrorLevel](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/UnitTest/NUnit/Common.fs#L105-105) | [DotCoverParams](http://fake.build/apidocs/fake-dotcover-dotcoverparams.html) | [Fake.DotCover](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/DotCover.fs)
[ErrorLevel](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/DotCover.fs#L28-28) | [NUnitParams](http://fake.build/apidocs/fake-nunitcommon-nunitparams.html) | [Fake.NUnitCommon](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/UnitTest/NUnit/Common.fs)

 I was trying to know if DotCover was passing its **Filter** to NUnit3 with a different name like **Params** or shadowing an existing name as it does with **ErrorLevel**. Thank you. Good day.

**Comment by matthid** [comment]
Because we changed several things in the reference documentation template I just wanted to add that this is actually quite easy to implement. What I would suggest is editing the index-template of the api reference page to append an appendix at the end with a list of modules/types all the required information is available in the razor-template.

**Comment by matthid** [comment]
@rmunn Do you think this has been solved with the modularization and the new reference documentation?
Personally, I'm more and more using the documentation pages instead of just looking up the code (which I'd assume is a good thing)

**Comment by rmunn** [comment]
It's certainly a lot better at this point; I just reproduced my initial search for `</>` and found it on the first try (I checked Modules, then IO, then Filesystem, and clicked on FileSystemOperators... and there it was).

However, I think the docs would still benefit from either an index or a search feature (or both!), so I'd be in favor of keeping this issue open until someone implements them.

**Comment by matthid** [comment]
@rmunn I'd just assume that this never happens :)
