### ISSUE TITLE
Update FAKE to latest FSharp.Core

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1527]
Otherwise we will get problems in our ecosystem, see https://github.com/tpetricek/FSharp.Formatting/pull/432

**Comment by forki** [comment]
Yes I tried. But I did not get it working. I'd love to see a pr on master

Am 23.04.2017 23:39 schrieb "Matthias Dittrich" <notifications@github.com>:

Otherwise we will get problems in our ecosystem, see
tpetricek/FSharp.Formatting#432
<https://github.com/tpetricek/FSharp.Formatting/pull/432>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsharp/FAKE/issues/1527>, or mute the thread

**Comment by matthid** [comment]
Don't worry it's more of a reminder. And if anyone takes it that'd be fine as well ;)

**Comment by matthid** [comment]
Apparently I did the update in https://github.com/fsharp/FAKE/pull/1281 already ... I just noticed this when the build went green on FSharp.Formatting :)

**Comment by matthid** [comment]
Interestingly I didn't noticed any problems in the "legacy" (non-netcore) FAKE...
