### ISSUE TITLE
FAKE 4.61.3, MSBuild Helper writes a warning into the error stream on Windows

### ISSUE THREAD

**Issue by andreichuk** [fsharp/FAKE#1573]
Hello,

FAKE 4.61.3 has a regression:
this line in MSBuildHelper.fs & MSBuild.fs
**traceFAKE "If you encounter msbuild errors make sure you have copied the required SDKs, see https://github.com/Microsoft/msbuild/issues/1697"**
writes the warning into the error stream on Windows which in its order causes problems in some build systems.

FAKE 4.61.2 works fine.

**Comment by matthid** [comment]
Actually FAKE prevents to write stuff to stdErr on Build Systems where this fails the build. What is your build system?

**Comment by matthid** [comment]
Relevant place is https://github.com/fsharp/FAKE/blob/5e78ad79e69e3c3bff23ad907594fa53b81e1304/src/app/FakeLib/TraceListener.fs#L124

**Comment by andreichuk** [comment]
https://github.com/Microsoft/vsts-agent
![image](https://cloud.githubusercontent.com/assets/2353790/26679202/beb03216-46dc-11e7-819e-fba7cc3c1160.png)
![image](https://cloud.githubusercontent.com/assets/2353790/26679225/d50c8154-46dc-11e7-8a02-c2cc0dce7a49.png)

**Comment by andreichuk** [comment]
> What is your build system?
team foundation

**Comment by matthid** [comment]
See https://github.com/fsharp/FAKE/issues/1574 for the follow-up on the general problem in this case.

**Comment by matthid** [comment]
Ok I'll leave this open as a reminder that a FAKE 4 hotfix might make sense.

**Comment by matthid** [comment]
@andreichuk is the 5.0.0-alpha010 release enough for you or do you need a hotfix for some reason?

**Comment by andreichuk** [comment]
I disabled "error on std error writes" then. i'll try FAKE 5 when it's at least in beta. thanks for your work!

**Comment by Slesa** [comment]
I just stumbled over this issue yesterday. Next step would be to migrate to FAKE5. But until then - what is the possibility to disable this error logging? Everything works fine, only this error message breaks the build. Do I have to recompile  FAKE locally?

Wouldn't it be nice to have an environment setting or something like that to prevent this error log?

**Comment by matthid** [comment]
@Slesa What is your build server? Why can't you disable that the build fails for writing in stderr?
Generally, the exit code should be enough for FAKE.

**Comment by Slesa** [comment]
The build server is TFS2017. I think, why I can't disable the failing is: I want to use the logging of the MSBuild mechanism for further analyzing, e.g. investigate the build quality, fill the result mail with correct data about warnings and all that stuff. As soon as I use the build batch build.cmd, this is prevented. The logging queue of msbuild is broken then. So I used the F# launcher of Isaac Abraham - and then the errror log stops the build. 

I just had a look at the options page, because your questioning made me feel I'd be missing something - and here it is: the option "fail on stderr" can be set, but only in batch mode. So, this is probably the reason why it works at all for me. Maybe Isaac should add that additional option, too?

**Comment by matthid** [comment]
We will revisit this for Fake 5. The Trace module is already a lot more flexible in that regard (ie you can register your own Listener and remove the default one).
I doubt that there  will be a FAKE 4 hotfix at this time.
