### ISSUE TITLE
Fake 5.0.0-alpha9 is throwing "no Fake Execution context was found" 

### ISSUE THREAD

**Issue by pkese** [fsharp/FAKE#1579]
### Description

Running a simple script is causing 

     System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: no Fake Execution context was found. You can initialize one via Fake.Core.Context.setExecutionContext

### Repro steps

1. clone https://github.com/pkese/fake-bugreport
2. `cd fake-bugreport\src`
3. run `fke`

### Expected behavior

Not throwing?

### Actual behavior

Throwing

### Known workarounds

Didn't find any

### Related information 

* Windows 10
* 5.0.0-alpha009
* net462 sdk

**Comment by matthid** [comment]
Ok the following works

```fsharp
(* -- Fake Dependencies paket-inline
source https://nuget.org/api/v2
source ../../../nuget/dotnetcore

nuget FSharp.Core

nuget Fake.Core.Targets prerelease
nuget Fake.Core.Tracing prerelease
-- Fake Dependencies -- *)

// include Fake lib
#r @"../packages/FAKE/tools/FakeLib.dll"
use execContext = Fake.Core.Context.FakeExecutionContext.Create false "path/to/script.fsx" []
Fake.Core.Context.setExecutionContext (Fake.Core.Context.RuntimeContext.Fake execContext)

//open Fake
open Fake.Core.Trace
open Fake.Core.Targets
open Fake.Core.TargetOperators

// Default target
Target "Default" (fun _ ->
    trace "Hello World from FAKE"

)


// start build
RunTargetOrDefault "Default"

```

Let me explain a bit:

- the `FakeExecutionContext` is just missing in the old runner, we should probably add that (which will make those lines unnecessary
- Because of `open Fake` you were actually mixing old and new implementation... Therefore you get ` Target "Default" is not defined.` or something similar when removing `open Fake`
- It's a bit unsatisfying that so many stuff needs to be opened, maybe we need to make the Targets system an exception to the rule. Or we suggest people to use

```fsharp

open Fake.Core

// Default target
Targets.Target "Default" (fun _ ->
    Trace.trace "Hello World from FAKE"
)

// start build
TargetOperators.RunTargetOrDefault "Default"

```

Obviously, I'd like to change those names a bit:


```fsharp

open Fake.Core
open Fake.Targets.Operators

// Default target
Targets.Create "Default" (fun _ ->
    Trace.trace "Hello World from FAKE"
)

// start build
Targets.RunTargetOrDefault "Default"

```

**Comment by matthid** [comment]
Should be fixed in alpha010. I also changed the `Targets` API to reflect my last example (+docs).

**Comment by matthid** [comment]
Have you tried to take a look at https://fake.build/fake-debugging.html#Run-script-without-fake-exe-via-fsi ? Last time I tried that it worked...
