### ISSUE TITLE
Need to package System.Reflection.Metadata, Version=1.4.1.0 in the tools directory

### ISSUE THREAD

**Issue by dsyme** [fsharp/FAKE#1603]
FSharp.Compiler.Service can need System.Reflecion.Metadata.dll .  This isn't being packaged in the ``tools`` directory.

This can lead to bugs like [this one](https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/pull/119#issuecomment-300753649)

**Comment by matthid** [comment]
It's because we need to handle and rewrite the fcs dll manually... This is really a mess in 4x.
I guess the netcore version 5x fixes this but type providers are missing.
We probably need to release a hotfix but I just wanted to point that out...(It will happen again for every dependency fcs introduces as long as it is only required "on occasion")

**Comment by yan0lovesha** [comment]
I am also having this issue for my project that needs to build fsx files to exe/dll. I see this error when FscHelperHelper.compile runs.

As a workaround I added a target in my build.fsx
```
Target "FixFakeBuildIssue" (fun _ ->
    [|  @"packages\System.Reflection.Metadata\lib\netstandard1.1\System.Reflection.Metadata.dll";
        @"packages\System.Reflection.Metadata\lib\netstandard1.1\System.Reflection.Metadata.xml" |] |> FileHelper.Copy @"packages\FAKE\tools"
)
```
Then make this target as the pre-step of the build target that will trigger this error. Then, it will copy these dependencies into Fake/tools folder before start building.

**Comment by matthid** [comment]
I'm closing this as there is in fact a workaround and I think FAKE 5 doesn't have this problem.
