### ISSUE TITLE
Make FAKE 4 docs available on GH Pages

### ISSUE THREAD

**Issue by Keraxel** [fsharp/FAKE#1614]
### Description

It is not possible to read FAKE 4 documentation on GitHub Pages. FAKE 5 is still in alpha state so one might not want to use this version yet.

**Comment by matthid** [comment]
I tried to link old and new docs back and forth (It's always the first line of a page). 
The old start page is still available via "Project -> Fake 4 Start page".

I think it might feel like information is lost because the navigation bar changed and is now on top. In fact all old information is still available and only navigation has changed. 
Sadly, I have no idea how the situation can be improved (while still pointing people to the new pages and give proper warnings). Any suggestion is welcome and PRs are probably accepted.

**Comment by forki** [comment]
IMHO the old docs should still be the ones that are visisble on first look. Since this is the released major

**Comment by matthid** [comment]
Ok I tried the following:
 - Replaced "Home" with a "Fake 4" Button
 - Added "Where is XYZ???" in the "Fake 4" menu which redirects to https://fake.build/help-docs.html
 - https://fake.build/help-docs.html is basically a the old sidebar linking to the current stuff
 - Fixed all old bookmarks with redirect pages to the new content

Please let me know if that helps
