### ISSUE TITLE
hasBuildParam is case sensitive, but target will be executed from args regardless of casing of args

### ISSUE THREAD

**Issue by Mnuzz** [fsharp/FAKE#1632]
### Description

hasBuildParam is case sensitive, but target will be executed from args regardless of casing of args. This caused some headaches due to an expectation of a clean build not actually occurring, despite logs suggesting that it does. There are some additional steps in our FAKE build script that run when hasBuildParam evaluates to true for some steps. So it is possible to have a case where only part of the intended effect of a build target actually happens. 

### Repro steps

This may be OS-dependent. Am using Mac OS X with Mono. 
Pseudocode for script is below
```
Target "Clean" (fun _ ->
    printfn "This is run when 'build clean' or 'build Clean' is called from command line"
)
if hasBuildParam "Clean" then
        printfn "This should run when 'build clean' is called, but only happens with 'build Clean'"

```

**Comment by Mnuzz** [comment]
Possible similar issue on another project: https://github.com/dotnet/corefx/issues/13146

**Comment by matthid** [comment]
Can you try to reproduce that again with latest?
Actually the internal architecture of this part changed massively with fake 5.
In fact `hasBuildParam` has nothing to do with running targets and just checks if a specific environment variable exists.
I don't think we actually set an environment variable named like the target, so that is probably set by you from outside? If yes I'm not sure how that relates to fake at all or why `hasBuildParam` and target casing is related.

Or on other words:
From FAKEs standpoint target-casing is irrelevant - that's just how it is implemented. If environment variables are case sensitive on your system that is a completely unrelated matter (imho)

**Comment by Mnuzz** [comment]
Holy blast from the past Batman.... wow.

**Comment by matthid** [comment]
@Mnuzz Yes trying to get the issue list cleaned up a bit ;)

**Comment by Mnuzz** [comment]
It's like a messy bedroom. Easiest if you clean it as you go
