### ISSUE TITLE
Any FAKE container available at GCR?

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1650]
### Description

I'd like to try to use FAKE to build F# projects, instead of albacore, to cut down on the number of dependencies.

Specifically, I'm bootstrapping a new build pipeline with Google's container builders: https://cloud.google.com/container-builder/docs/concepts/build-steps

Is there a FAKE docker container available that I can use to invoke a build of a single repo? The repo is structured like the project bootstrap repo or the suave-fable scaffold.

In the end, I'd like a command step like:

```yaml
steps:
- name: docker.io/fsharp-fake/fake
  id: paket
  args:
  - release
```

References:

 - https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/csharp/dotnet/examples/TestApp-2.0/cloudbuild.yaml
- https://fsprojects.github.io/Paket/paket-and-dotnet-cli.html
- [FAKE portable][fake-releases]

 [fake-releases]: https://github.com/fsharp/FAKE/releases

**Comment by matthid** [comment]
The problem with a fake container is that fake is often used to execute other tools, which would be a bit difficult when the container is minimal.

**Comment by haf** [comment]
It would in this case just need:

 - a runtime, `dotnet` (core)
 - itself

I don't see the problem.

**Comment by matthid** [comment]
It should be very easy to build, it's just that I don't really see the use-case. Maybe I'm blind :)
Obviously we could say in some future world we only need `dotnet` and download the rest, but I have not seen a project where this is true yet.

However, you are not blocked here. Just use the `dotnet` docker image as base and download the latest binary distribution from github (https://github.com/fsharp/FAKE/releases/download/5.0.0-alpha015/fake-dotnetcore-portable.zip) and then start fake via `dotnet <path to fake.dll> <fake arguments>` or include a wrapper script.

**Comment by haf** [comment]
Did you read the docs I linked to? The use-case is cloud-native apps, where you don't have any external tools to run; and when you do you can run them as command-lines through containers.

**Comment by matthid** [comment]
Yes what I'm trying to say is that we can never provide a docker container working for everyone, because in your F# script you can do everything. And as FAKE is so easy to install it's most likely easier to extend another container to include FAKE than to extend a minimal FAKE container.

Consider fable where we want to call NPM from the F# script. We cannot really call tools outside of the container/the host/different container. And if we consider including NPM where do we stop?

So while I agree that we probably should provide such a container I think it's only useful in very limited scenarios (which the one you suggest probably is). Therefore it isn't a high priority right now (obviously I would accept a PR). 

Is this reasoning sound? I just fear that it might confuse some users and gets us lots of new issues :)

**Comment by haf** [comment]
It's a good question. I think a fable container is a good idea as well, but that's separate from a FAKE container and it's a legitimate case to create another docker container.

I think you should stop when it's enough; FAKE on top of dotnet core and Fable is probably it.

Yeah, this is a topic for discussion and if I need it I'll build one myself and PR it. I'm just gauging the interest and I appreciate your feedback.

**Comment by matthid** [comment]
Did you ever try to build one?

It should be as simple as:

```
FROM dotnetcore
RUN curl https://github.com/fsharp/FAKE/releases/download/5.0.0-alpha015/fake-dotnetcore-portable.zip
RUN unzip fake-dotnetcore-portable.zip
RUN dotnet fake/fake.exe --version
```

**Comment by matthid** [comment]
Closing this feature request for now. I think creating a docker image is quite easy and we might publish one eventually when we have a stable fake 5 release.
