### ISSUE TITLE
Process execution on mono broken?

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1713]
### Description

Having upgraded to FAKE 5 and followed deprecation advice, I now have `Shell.Exec` calls that fail on Mac because `mono` is not used to invoke them. Worse, the `xUnit2` function seems to suffer from the same problem.

### Repro steps

1. Use FAKE 5
2. Use `Shell.Exec` to start a .NET binary
3. Run build on Mac

### Expected behavior

The old behavior was that mono was used to start the process.

### Actual behavior

Failing to start the exe directly as you'd expect.

### Known workarounds

For `Process.Exec` one can specify `mono` explicitly. However, this could then break the build on Windows. For `xUnit2` I am not sure how to work around.

### Related information 

* Mac
* Latest FAKE 5

**Comment by matthid** [comment]
Yes it looks like this has worked for dotnetcoreapp1.0 and was changed there. But indeed we changed this as well. Additionally, I already noticed this particular change in behavior because of bootstrapping and errors on travis after updating FAKE 5 alpha to beta. So I hope we can fix this with https://github.com/fsharp/FAKE/pull/1697

But it is nice to have some confirmation around this.

**Comment by matthid** [comment]
I think this is solved with https://github.com/fsharp/FAKE/releases/tag/5.0.0-beta008
