### ISSUE TITLE
Ways to help contribute

### ISSUE THREAD

**Issue by vanceism7** [fsharp/FAKE#1751]
Hey guys, I wrote in gitter and @matthid suggested I open an issue. This is my first time getting involved in OSS and was just wondering if there was anything in specific that needs to be done that I could help with. I read the contributing page as well as the API changes guidelines and so fourth, I've also seen the curated issues list as well. Just looking for a little direction as I get started, whatever I could do to help, that would be awesome. I love F# and want to help the language grow 

Thanks!

**Comment by matthid** [comment]
Hey @vanceism7, yes we appreciate help everywhere.
Usually it starts by using the stuff on your own projects (FAKE/Ionide/FSharp.Formatting/...). Then you report issues and contribute fixes and maybe features and fix/improve documentation. If you stay in the game for a while you will be asked to join the maintainers squad ;).

It's really straight forward and we don't have any specific process to follow. 
Is there anything special you want to know?

**Comment by vanceism7** [comment]
Oh ok gotcha. No, that all makes sense, I was just wondering if there was any sort of official process or set of higher priority items to work on. I read that there were a lot of old fake 4 modules that still needed to be ported to fake 5. I'm not sure what the status of that is, but I'll just start off with building and using the app and then go from there with issues/PRs for whatever I run into. Thanks @matthid

**Comment by matthid** [comment]
Yes we have several important points:
 - Make FAKE 5 scripts work with tooling (either VS2017, Ionide or something)
 - Port more modules (the more we have ported at release the better the adoption will be (at least that's what I'm assuming)
 - Docs, the more straight-forward the upgrade process is the better

I think we can release FAKE 5 once the first point is sorted out (we can do the others along the way). However, I was asked to wait for a release a bit until global tools (introduced with some new sdk-cli version). Which makes sense because a lot of people might want to use that way to install FAKE 5 into their projects. So this is another point to investigate.

So as you can see the answer is everywhere ;)

**Comment by vanceism7** [comment]
Ok great, I think that gives me enough of a starting point to get into it. Thanks for all the info
