### ISSUE TITLE
Provide an option to install Fake.dll (portable) using Paket

### ISSUE THREAD

**Issue by pkese** [fsharp/FAKE#1773]
### Description

According to instructions in #1765, I'm now trying to move to "netcore-fake", but there appears to be no migration path for Paket users:  
There appears to be no way to install any sort of Paket compatible Nuget package that would distribute a `Fake.dll` which one could run using `dotnet fake.dll`.

### Repro steps

Add `nuget FAKE<anything> prerelease` to `paket.dependencies`.  
Run `paket update && paket install`  

### Expected behavior

Have `Fake.dll` available anywhere in `./packages`

### Actual behavior

`Fake.dll` nowhere to be found.

### Known workarounds

Manually download `fake-dotnetcore-portable.zip` from https://github.com/fsharp/FAKE/releases 

### Related information 

* Operating system: Windows 10
* Revision: 5.0.beta12
* .NET Runtime, CoreCLR or Mono Version: 2.0.x

**Comment by matthid** [comment]
I think the dotnet-fake package should work with the paket reprotools feature?

**Comment by matthid** [comment]
the csproj is the nuget way. paket will hopefully support cli tools soon.
/cc @enricosada @forki

**Comment by matthid** [comment]
Personaly I have no objections in providing just another nuget package containing everything, but it feels wrong...

**Comment by matthid** [comment]
I'm closing this for now, as I think the correct thing to do is to use 
```
repotool dotnet-fake
```

once we have https://github.com/fsprojects/Paket/pull/2938

However, like stated above I'm not against releasing just another package if after the above PR we still feel the need. The current workaround is to use `curl` and the portable release, a `csproj` file or the global fake installation.

Feel free to suggest otherwise.
