### ISSUE TITLE
I'm having a hard time wrapping my head around FAKE 5.0

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/FAKE#1852]
Why should FAKE 5.0 be different from every other package I download from Nuget.org via Paket?

This is what I especially don't like/understand:

> DISCLAIMER: These scripts have no versioning story. You either need to take care of versions yourself (and lock them) or your builds might break on major releases.

My workflow is to handle versioning with Paket and building with a Build.fsx FAKE file. Requiring me to install FAKE with choco (or something else) and keep track of FAKE versions outside of my projects adds (what I consider) unnecessary complexity.

Please explain what benefit dealing with this complexity, and potentially altering my established workflows, gives me.

So far I have been testing FAKE 5.0 by adding the many required beta packages to my paket.dependencies file. Apparently this is somehow incorrect or not fully functioning.

I've come around to the idea that the added complexity of multiple FAKE packages will someday, somehow benefit me, but I do not understand the benefit of installing FAKE as an app.

**Comment by matthid** [comment]
You can still manage your dependencies with paket. Also there are alternative ways to use fake 5. Chocolatey is only one

**Comment by matthid** [comment]
> Please explain what benefit dealing with this complexity, and potentially altering my established workflows, gives me.

Fake 5 gives you the opportunity to work without paket in a more lightweight way. The current "way" is just because of technical reasons. In .net core you have two deployment options:
 - SCD (self-contained-deployment): These deployments can run by themself (ie have ".exe") but are framework dependent -> Therefore packaging in a NuGet package doesn't make too much sense
 - FDD (framework dependent-deployment): These deployments can run via `dotnet fake.dll`. This is basically the content of `fake-portable.zip` on the release page.

We could package a FDD deployment in a NuGet package, but then you still need to manage the .NET Core dependency yourself.  But actually that deployment option is in fact missing on NuGet at the moment. /cc @enricosada is there documentation around the IsTool flag you were talking about on fsharpx?

So with either option you need to take care of an additional dependency (either FAKE or .NET Core). I hope that makes sense.

> DISCLAIMER: These scripts have no versioning story. You either need to take care of versions yourself (and lock them) or your builds might break on major releases.

This is only a warning.

> So far I have been testing FAKE 5.0 by adding the many required beta packages to my paket.dependencies file. Apparently this is somehow incorrect or not fully functioning.

Yes. The migration page states this: https://fake.build/fake-migrate-to-fake-5.html
You should stay on `fakelib.dll` until you have fixed all warnings and then move to the new runner.

**Comment by matthid** [comment]
Ah and I forgot that you can add
`clitool dotnet-fake`
to your paket dependencies file to manage fake version via paket.

**Comment by matthid** [comment]
Played a bit around and maybe the following setup is what you are trying to achieve: https://github.com/matthid/fake-bootstrap/tree/paket_clitool. Will probably add this to the documentation as just another way.

**Comment by matthid** [comment]
see https://chocolatey.org/packages/fake
I’m not sure how you got 3.7.4 I don’t see it in the versions...

Obviously this repository. Fsharp.Formatting and Mechanic has an open PR. More are likely to follow soon.

**Comment by jackfoxy** [comment]
choco worked this time
