### ISSUE TITLE
FAKE5 Getting Started Guide is outdated

### ISSUE THREAD

**Issue by mclang** [fsharp/FAKE#1854]
I noticed some things in [FAFE - Getting started](https://fake.build/fake-gettingstarted.html ) guide are outdated, at least when using FAKE v5.0.0-rc001

This doesn't work:
```
Target.create "BuildApp" (fun _ ->
  !! "src/app/**/*.csproj"
    |> MSBuild.runRelease buildDir "Build"
    |> Trace.Log "AppBuild-Output: "
)
```

Later it is written differently, but also this doesn't work:
```
Target.create "BuildApp" (fun _ ->
   !! "src/app/**/*.csproj"
     |> MSBuild.runRelease buildDir "Build"
     |> Trace.logItems "AppBuild-Output: "
)
```

It seems that what previously was `MsBuild.MsBuildRelease` and `Trace.Log` is now `MSBuild.runRelease` and  `Trace.logItems`, and that now you need to define `setParams` function for the `runRelease` and `runDebug` functions.

I haven't found out yet how to get things running, so can't do PR of the needed changes myself

**Comment by matthid** [comment]
Thanks for reporting! And yes the replacements you suggest are the correct ones afaics. `setParams` probably will be `id`.

> I haven't found out yet how to get things running, so can't do PR of the needed changes myself

Not sure if you mean "I don't know how the working script should look like" or "I don't know how to get documentation running locally.

Just in case it is the second: You don't need anything working in order to improve docs. For example you can use the github web:
![image](https://user-images.githubusercontent.com/1866463/38496123-9fa2f21c-3bfc-11e8-84c3-af4332fdca37.png)

**Comment by matthid** [comment]
> Why do you need one anyways when previously you could get started simple?

Problem was that previously there was no way to set msbuild parameters when using "globbing" now there is.

> because I haven't yet found documentation how to create one.

Just using `id` as argument should work and give the defaults?
There is some documentation here: https://fake.build/apidocs/fake-dotnet-msbuild.html

**Comment by mclang** [comment]
Thanks, getting forward now.
