### ISSUE TITLE
Convert Fake.IO.FileSystem/Shell.fs to "module based"

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1879]
### Description

Is someone working on converting [Shell.fs](https://github.com/fsharp/FAKE/blob/master/src/app/Fake.IO.FileSystem/Shell.fs#L16) to "module based" API ?

Converting from `Shell.CopyFile` to `Shell.copyFile`.

If not, I can do it.

**Comment by matthid** [comment]
Feel free to do so. One note however: as we are in RC now, we try to not introduce breaking changes anymore. This means we probably would need to work with `Obsolete` attribute ...

**Comment by MangelMaxime** [comment]
I can duplicate the code to use the `Obsolete` attribute it's just feel strange to have all the module converted except this one. At least in my `build.fsx` this is what I see.

**Comment by matthid** [comment]
Yes I agree :)
On the other side it will look a bit weird in intellisense (but I probably would be fine with that)...

Honestly I thought about the "Shell" module as just a bunch of functions without any real place (or at least I have not found the real place for them). Usually they do not compose well with other parts and look weird, yes.

**Comment by MangelMaxime** [comment]
Indeed they are specials functions but really useful or at least I use them in all my build scripts. Perhaps there is equivalent in the others modules I don't know.

For the intellisense I prefer a clean intellise but can live have both PascalCase and camelCase. 

Just one question, if we mark them as obselete when do you plan to remove the PascalCase ? Just asking if we are not going to have them arond for a while. Instead of having a "last small" breaking change to make the user experience consistent.

**Comment by matthid** [comment]
> Just one question, if we mark them as obselete when do you plan to remove the PascalCase ?

Fake 6 will remove old runner and all legacy stuff, therefore that would be the next opportunity to remove obsolete stuff. It will take **at least** another year.

> Instead of having a "last small" breaking change to make the user experience consistent.

Yes the problem is there will always be one more small breaking change considering the state of the code ;). The good thing is: If we are now unhappy with a module we can create a new one and let the old one die, which we could never do before.

I know what you mean but I'm afraid that `Shell` is used quite a lot and considering the message I have given about breaking changes in the RC-phase we cannot do it anymore ;)
(I probably would think differently about other stuff)
