### ISSUE TITLE
Referencing any f# library causes FAKE 5 script to fail with FileNotFoundException

### ISSUE THREAD

**Issue by OlegZee** [fsharp/FAKE#1888]
### Description

I cannot use the functions I implemented in F# library.

### Repro steps

1. create samplelib project (make folder, issue `dotnet new classlib -lang f#`) and build it

2. take https://github.com/matthid/fake-bootstrap (master branch)

3. Paste the following code to myscript.fsx

```fsharp
#r "paket:
nuget Fake.Core.Target //"

#I "C:/projects/samplelib/bin/Debug/netstandard2.0"
#r "samplelib.dll"

open SampleLib

Say.hello "world"
0
```

4. follow fake-bootsrtap's readme.md to bootstrap the project

5. run the script `dotnet fake run myscript.fsx`

### Expected behavior

Script prints "Hello world" to console.

### Actual behavior

Script fails with the following text trace:

```
C:\projects\fake-bootstrap>dotnet fake run myscript.fsx
-> FileNotFoundException: Could not load file or assembly 'samplelib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
-> FileNotFoundException: Could not load the specified file.
Performance:
 - Cli parsing: 216 milliseconds
...
```

### Known workarounds

In the regular f# project I noticed similar issue connected with different FSharp.Core versions which I fixed by using paket (added fsharp.core and added redirects: force to deps file).

### Related information 

* Windows 10
* FAKE 5.0.0-rc001
* dotnet 2.1.2

**Comment by matthid** [comment]
Oh, any reason to not use new packages feature?

**Comment by matthid** [comment]
The ugly workaround is probably to use `--fsiargs`. But yes it will probably take a bit of work to get that running and I'm not sure it's worth it ...

**Comment by OlegZee** [comment]
@matthid, thank you for prompt reply.
I will try making a package. Could you please explain `--fsiargs` approach?

I need this option for developing/debugging the library.

**Comment by OlegZee** [comment]
Here're the steps I made:

* build package for samplelib by `dotnet pack -c Release`
* copied nupkg file to pkgs folder next to myscript.fsx
* updated myscript.fsx to:
```
#r "paket:
source https://api.nuget.org/v3/index.json
source pkgs
nuget samplefslib //"

open SampleFsLib

Say.hello "world"
0
```

Still no luck:

```
 - Runtime: 3 seconds
Script failed
-> Compilation failed:
   C:\projects\fake-bootstrap\myscript.fsx (6,5)-(6,16): Error FS0039: The namespace or module 'SampleFsLib' is not defined.
   C:\projects\fake-bootstrap\myscript.fsx (8,0)-(8,3): Error FS0039: The value, namespace, type or module 'Say' is not defined.
```

**Comment by matthid** [comment]
@OlegZee Yes you probably need to delete the `<script>.lock` file first for fake to pick up new or updated dependencies.

Regarding the `--fsiargs`: 
Try the following `dotnet run --fsiargs --reference:C:/projects/samplelib/bin/Debug/netstandard2.0/samplelib.dll myscript.fsx`, which should - in theory - work

**Comment by OlegZee** [comment]
@matthid Thank you for input.
Though I failed to get this `--fsiargs` running (with the same error)  and local package references does not seem to work within `#r "paket:...` I managed to reference my assembly via project-wide paket.dependencies.
This is pretty cool as I can keep going on integrating my Xake with FAKE 5.

**Comment by matthid** [comment]
Let me keep this open to investigate the fsiargs situation and to see if we can improve the situation (for example to yield a warning). Thanks for reporting back your workarounds.

**Comment by matthid** [comment]
* You consider the lockfile an issue? Yes imho it should be checked in because you want that other developers/machine execute with the same versions. Otherwise your script will break when someone releases a breaking change...

* It is aleady historic, but we did it because of intellisense. maybe we can indeed add “framework netstandard20” by default (as long as the intellisense script is still correct)

* You mean do **not** work?

Thanks for this input. In fact I’m currently looking into the performance and this would in fact be an potentially easy win

**Comment by OlegZee** [comment]
I mean it DOES work in both cases and that's really cool.

**Comment by OlegZee** [comment]
* huge lock file is an issue IMO because it will change frequently and will flood the code review UI (in bitbucket and likely github). `framework: netstandard` does definitely fix the issue.
* intellisense works fine

**Comment by matthid** [comment]
New fake version rc010 has several performance improvements built in. Including the `framework: netstandard2.0` lets see if people report issues.

**Comment by matthid** [comment]
Just one note on this, we will soon have https://github.com/fsharp/FAKE/pull/1903/commits/e50d80c3734771348ba9661acd7d0d67329c663d in order to document how to test stuff locally. But this issue with `#r` still kind of disturbs me for several reasons:

- I'd like to "make it work", however the combination of how intellisense and FAKE interact with each other make it quite hard for a user to properly add the `#r` because the user needs to add the proper `#if #else` stuff as well
- Adding an warning could be frustrating (and probably is not as easy as I'd like)

But realistically we will probably go with the warning :/

**Comment by Danl2620** [comment]
@OlegZee Hi, what steps did you take to solve the issue you outlined in https://github.com/fsharp/FAKE/issues/1888#issuecomment-385061951 (if you did solve it)?

**Comment by OlegZee** [comment]
Hi @Danl2620! I haven't touched this since then. I'm just using FAKE CLI to run the scripts.
