### ISSUE TITLE
Fake5: GitVersion not called with mono

### ISSUE THREAD

**Issue by seanamosw** [fsharp/FAKE#2041]
### Description

When using `Fake.Tools.GitVersion.generateProperties` on non-windows machines, `GitVersion.exe` is not called with mono.

Fake4 has the correct behaviour.

### Expected behaviour

```fsharp
let version = Tools.GitVersion.generateProperties id
```

```
mono xxxx/GitVersion.exe
```

### Actual behavior

```fsharp
let version = Tools.GitVersion.generateProperties id
```

```
xxxx/GitVersion.exe

Script reported an error:
-> Start of process 'xxxx/GitVersion.exe' failed.
-> Win32Exception: Permission denied
```

### Related information 

* Fake.Tools.GitVersion 5.2.0

**Comment by matthid** [comment]
The current workaround would be to just copy the fixed version into your script file until the fix is released (which will be next week once https://github.com/fsprojects/Paket/pull/3307 is released). Alternatively, you can depend on the staging nuget feed (but be aware that we only keep a couple of version there): https://www.myget.org/F/fake-vsts/api/v3/index.json (use update to the alpha version of Fake.Tools.GitVersion)

**Comment by matthid** [comment]
(will take a couple of minutes until the build finished and the fixed version is available)
