### ISSUE TITLE
Shouldn't Fake.DotNet.FSFormatting depend on FSharp.Formatting?

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsharp/FAKE#2043]
And I think it should use the FSharp.Formatting library instead of the command-line tool.

**Comment by matthid** [comment]
Maybe, but for this FSF needs to compile and run on .net standard. And nobody has done the work for that yet. In the end I'd say this is not really an issue here in fake :)

**Comment by teo-tsirpanis** [comment]
Actually, FSharp.Formatting _can_ run on .NET Standard. .NET Framework libraries work on .NET standard 2.0. But there are two caveats here:

* Would FSharp.Formatting _actually_ work? A .NET Standard 2.0 project that references it just _compiles_, but what if it uses a .NET Framework-specific API? Pretty unlikely IMHO, but I will raise an issue over there as well.
* As I saw, FAKE packages target .NET Standard 1.6, .NET Standard 2.0, and .NET Framework 4.6. This would mean that the FSharp.Formatting package would need to drop .NET Standard 1.6, but thanks to FAKE's modularity, only this, and the other FAKE packages that depend on it would be affected.

  Is that a breaking change?

  Yes it is, but who is actually using .NET Standard 1.6? With half the API surface of its predecessor, isn't it considered legacy? Besides, the FAKE executable itself runs under .NET Core 2.1, which I think should not cause a problem.

  Regardless, dropping .NET Standard 1.6 for a few packages has important ramifications, I think that it should happen on FAKE 6 (in this case, on _all_ FAKE modules). It would make the codebase much more flexible.

**Comment by matthid** [comment]
I don't think using the "feature" to use full framework assemblies on netstandard20 is a good idea. And it is not supported by paket. So the way forward is to make FSF compile on netstandard20.

Regarding the drop of netstandard16 I don't think it is a problem for single packages, yes it is breaking but only if people are actually using it, which is very unlikely for this particular package.

So sending a PR to fsf and then to fake is the way to go.
I will probably not accept a pr adding full framework dependencies here (because as you have already noted it might compile but fail at runtime in particular places and I don't want to debug stuff the compiler could have told me). 

Regarding dropping netstandard16 for fake 6 - yes that might be an option but to do that we would need to make sure we educate our users to use `~> 5.0` for all dependencies

**Comment by matthid** [comment]
> educate our users to use `~> 5.0` for all dependencies

Or maybe not. Honestly I don't think anyone uses netstandard16 anyway.

**Comment by matthid** [comment]
> Paket happily does the trick in a library of mine. 😂

That's kind of by accident because we forward the final resolution to NuGet. In fact if `FSharpx.Collections` would have some additional transitive dependencies and would put them in a `netX` group (as it should). Paket would not manage them, instead you would get some version resolved by NuGet I'd assume

**Comment by teo-tsirpanis** [comment]
> That's kind of by accident

I see... Fun fact: [this is the second time I encountered something like this](https://github.com/fsprojects/Paket/issues/2333#issuecomment-303229110).

**Comment by matthid** [comment]
@teo-tsirpanis Yes I'm sorry to break your stuff but ... it seems you have a tendency of abusing stuff (just like myself by the way ;) ). Forwarding everything to NuGet simplifies a lot of stuff at paket but things like these where stuff is somehow magically working which shouldn't actually work is a side-effect of using dark-side nuget.
