### ISSUE TITLE
Referencing SocketsHttpHandler in Fake 5.3

### ISSUE THREAD

**Issue by theimowski** [fsharp/FAKE#2050]
### Description

Hi, is it possible to reference SocketsHttpHandler (introduced in .NET Core 2.1) using Fake 5.3 as global tool?

### Repro steps

Create file `http.fsx`:

```
#r "paket: nuget System.Net.Http //"
#load "./.fake/http.fsx/intellisense.fsx"

#if !FAKE
#r "netstandard"
#r "Facades/netstandard"
#endif

open System.Net.Http

let url = "https://fake.build"

let httpHandler = new SocketsHttpHandler()

let client = new HttpClient(httpHandler)
```

Run `fake run http.fsx`

### Expected behavior

Would be nice to compile

### Actual behavior

```
Script is not valid:
	$dir/http.fsx (13,22)-(13,40): Error FS0039: The type 'SocketsHttpHandler' is not defined.
``` 
### Related information 

```
> dotnet --version
2.1.301
```

```
> fake --version
FAKE 5 - F# Make (5.3.0)
```

**Comment by matthid** [comment]
I guess the reason is that we compile the script as netstandard20 library (for technical reasons).

You probably can use reflection as we are already runnung on 2.1, see https://github.com/fsharp/FAKE/blob/release/next/src/app/fake-cli/fake-cli.fsproj

I don't have any plans to change that as it will complicate some thing for not a lot of gains...

 Isn't the sockets http handler the new default anyway?

**Comment by matthid** [comment]
See also https://github.com/fsharp/FAKE/issues/2029 and the linked issues

**Comment by theimowski** [comment]
It is the default handler yes, but I want to test it with custom properties set.
Do you know if I could run such script with fsi?
If not I'll go with a console app not to use reflection

**Comment by matthid** [comment]
Honestly, if you don't have any particular properties in mind just use the default httphandler as it will forward everything to the sockethttphandler anyways, see https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Windows.cs

**Comment by theimowski** [comment]
I do want to try out `MaxConnectionLimit`, `PolledConnectionLifetime` etc.

**Comment by matthid** [comment]
Yes then I guess console application is your best bet, we will have it available in fake once the API is part of a netstandard...

**Comment by matthid** [comment]
I guess we can close this. I feel like limiting scripts to netstandard instead of depending on a particular platform makes sense. It allows us to have other distributions of the fake runtime if we need them (on the full framework/mono). It makes the runtime technically simpler because you only need the netstandard reference assemblies.

However, if requests like this come for several APIs we might rethink this.
