### ISSUE TITLE
Processing Target Parameters

### ISSUE THREAD

**Issue by bratfizyk** [fsharp/FAKE#2151]
I've found out it is possible to pass in parameters to my targets by using ```Target.runOrDefaultWithArguments```. Then I can invoke my Target with a list of args like this:

`./fake.sh build -t Test -arg1 val1 -arg2 val2 -flag1 -flag2`

Is there a decent way of handling those arguments from within targets ? For now the best I was able to come up with myself is:

```
let tryGetArgument arg args =
    let rec tryFind = function
        | [] | [ _ ] -> None
        | name :: v :: _ when name = arg -> Some v
        | _ :: xs -> tryFind xs
    tryFind args

Target.create "Test" (fun args ->
    printfn "%A" args.Context.Arguments
    printfn "Found: %A" <| tryGetArgument "-t" args.Context.Arguments
)
```
(Note that it handles single-value parameters, no flags, but that's fine for my needs for now).

Also, I've found out there's a package like this:
https://fake.build/core-commandlineparsing.html
But I found it way too complex for my needs. I would be fine with a much more lightweight solution.

**Comment by matthid** [comment]
I guess you have to define what "lightweight" means. I think defining a single string and then using a normal `Map<string, string>` like datatype as lightweight as it can get ;)

Also people have different opinions on how a "lightweight" library might look like, for example what you suppose are arguments which are not POSIX conform and therefore nothing I'd like people to use by default.

**Comment by BlythMeister** [comment]
Args could be added as fakevars automatically...

**Comment by BlythMeister** [comment]
I guess the arguments are already provided, it's more the mechanism to find them.  Nothing stopping us adding a function onto the context to get named argument I guess.

**Comment by matthid** [comment]
Problem is that if we point people into that direction we will get issues about using the CLI incorrectly and reporting issues.
For example: If people use `fake run build.fsx --fsiargs --debug` we will assume `--fsiargs` to be a script arguments (because if it is a "run" argument it needs to be "before" `build.fsx`).
With the default settings and the way I suggest fake will report an error about an additional unrecognized argument (which hints the user into his mistake), if we simple collect arguments and wait for users to use them without reporting errors users will assume it is a fake problem when it is not.

**Comment by BlythMeister** [comment]
Ahh I see the issue.
I've never used the arguments like this, ive always set environment variables in my scripts before calling fake...and then pull them out in fake.

**Comment by bratfizyk** [comment]
@matthid By "lightweight" I meant that I've had hard time trying to define the usage string in order not to get an exception into my face ;). But looks like I'll need to spend more time with a doc.

Thanks for the info. From what you've said I guess that using Docopt is the recommended way to go. Let me take a closer look and I'll come back to the discussion soon.

**Comment by matthid** [comment]
@bratfizyk I'm happy to extend the section with more examples or whatever you think might help. I'm also open for other APIs as long as my points from above are addressed somehow. In fact you can easily roll your own without my intervention by publishing a NuGet package, we already link other "external" modules in the modules menu, so that could work as well.

**Comment by bratfizyk** [comment]
OK - I've played a bit more with the Docopt and I must admit I had underestimated it. The "formatting string" serves an additional role, that is forcing a user to write a documentation. I think I've understood the way it should be used and I like it.

Happy to close the issue now - not much more to say ;). Thanks for the help.

**Comment by matthid** [comment]
@bratfizyk please feel free to suggest changes or send updates to the corresponding places such that others find the answers faster :)

**Comment by bratfizyk** [comment]
I think it's all in the right place - the problem was rather with me being a bit too impatient ;).
But sure - I'll be happy to post some updates if anything comes to my mind.
