### ISSUE TITLE
MSBuild --no-restore cli argument is not available despite a DoRestore option

### ISSUE THREAD

**Issue by Danl2620** [fsharp/FAKE#2226]
### Description

Using the `DotNet.build` or `DotNet.build` it is not possible to pass through the `--no-restore` flag, despite the `MSBuild.CliArguments` type having a `DoRestore` member.

### Repro steps

Create a build target like so:

```
Target.create "Build" (fun _ ->
    !! "TestProject 
    |> DotNet.publish (fun (info:DotNet.PublishOptions) -> 
        { info with
            MSBuildParams = { 
                MSBuild.CliArguments.Create() with 
                    DoRestore = false
            }
        })
)
```

### Expected behavior

The build process would not do a restore before building.

### Actual behavior

The build process does a restore.

### Known workarounds

None that I am aware of.

### Related information 

* Operating system: macOS
* .NET Runtime, CoreCLR or Mono Version: .netcore 2.1
* Version of FAKE (4.X, 5.X): 5.11.1
* (if performance issue) Performance information, links to performance testing scripts: slow builds when doing quick local iteration.

**Comment by JarnoNijboer** [comment]
You can set it as a MSBuild param. Thats the way I use it

**Comment by Danl2620** [comment]
Can you give an example?  I'm not seeing a way in the source...

**Comment by matthid** [comment]
I think this particular edge case is a bit of a pain.
Afaik when using the `msbuild` cli then `--no-restore` is the default and you need to use `/restore` to enable restore.
When using the `dotnet` cli its exactly the reverse. It will use `/restore` by default and skip it if `--no-restore` is given.
Therefore, I feel like we need to add `--no-restore` to the dotnet cli instead of adding it to `MSBuildParams`. We can either add it to `DotNet.Options`

https://github.com/fsharp/FAKE/blob/bcbe8b3e1b772084b9cfb2667decd8e00b2fa35c/src/app/Fake.DotNet.Cli/DotNet.fs#L467-L487

But I don't think you can use `--no-restore` on all commands. Therefore it needs to be added to every command manually. We already have this for `dotnet test` but need to add it to others: 

https://github.com/fsharp/FAKE/blob/bcbe8b3e1b772084b9cfb2667decd8e00b2fa35c/src/app/Fake.DotNet.Cli/DotNet.fs#L1288-L1327

**Comment by matthid** [comment]
By the way current way to do this is to use the `Common.CustomParams` field:

https://github.com/fsharp/FAKE/blob/bcbe8b3e1b772084b9cfb2667decd8e00b2fa35c/src/app/Fake.DotNet.Cli/DotNet.fs#L539-L544

**Comment by Danl2620** [comment]
Thanks!  I used `withCustomParams` and my particular case is solved:

```
Target.create "Build" (fun _ ->
    !! "TestProject 
    |> DotNet.publish (fun (info:DotNet.PublishOptions) -> 
        { info with
            Common = DotNet.Options.withCustomParams ("--no-restore" |> Some) info.Common
        })
)
```
