### ISSUE TITLE
Building Precompiled Azure Functions with FAKE + Paket

### ISSUE THREAD

**Issue by Angr1st** [fsharp/FAKE#2233]
### Description

When I try to use FAKE and Paket to build my F# Azure Functions all my functions won't get indexed by the Azure Function Runtime V2. Using regular NuGet everything works like a charm. The only differences are the way the nuget Packages are defined and that I'm using FAKE.

### Repro steps

Clone this Sample Repo (https://github.com/Angr1st/AzureFunctionFAKEPaket)

1. execute dotnet build

2. start the azure function runtime (func start) inside the bin/debug/netcoreapp2.1/ Folder

3. See that all Functions get registered properly

4. Stop Azure Function Runtime

5. Checkout the 'Fake' branch

6. run ./fake.cmd/sh build

7. start the azure function runtime (func start) inside the bin/debug/netcoreapp2.1/ Folder

8. See that all Functions don't get registered properly

### Expected behavior

That both cases work. All Azure Functions are registered properly when using FAKE + Paket to build them.

### Actual behavior

Using FAKE + Paket creates Azure Function dll that the runtime can't handle as it is unable to register the Functions. 

### Known workarounds

Stick with Nuget and avoid FAKE.

### Related information 

* Operating system: Windows 10 1803
* Nuget Package 5.11.1
* CoreCLR 
* Medium
* Version of FAKE (5.X)

**Comment by Angr1st** [comment]
Well If it isnt could you explain what you mean by 'downgrading' would it
be enough to place the correct 'global.json' in the project-dir or would
setting the DotNet.BuildOptions.runtime (If this would be able to set the
sdk version) inside the build.fsx or would I need to completly uninstall
und Reinstall the dotnet SDK?

It still strikes me as odd that It works without a Problem when Not using
Fake and Paket...

Steffen Forkmann <notifications@github.com> schrieb am Fr., 11. Jan. 2019,
07:28:

**Comment by forki** [comment]
As you can see in the linked issue the problem also happens to user that don't use paket nor fake. 

Please take a look into your paket.lock file and see that you referenced all kinds of asp.net core 2.2 libs. That's because paket in default mode tries to get you the latest version that matches the dependency criteria (especially important are the ones that are specified in azure functions own nuget file). Nuget.exe in contrast resolve to the oldest matching. That's why they work for you in that particular case (and which creates issues in other areas). Both resolution strategies have advantages and disadvantages. In paket you can select the resolution strategy on many different levels. Anyway since this is platform problem I recommend to specifically pin asp.net core libs to 2.1 in your paket.dependencies file and run paket install again.

**Comment by matthid** [comment]
I think this is a paket issue if this is an issue at all... 
@Angr1st Please re-open in paket if you think this is not solved by the suggestion from @forki

Also fake can be used without the need to change your projects to paket.

**Comment by Angr1st** [comment]
Thanks for your helpful hints anyway 👍  I got it working 
`nuget Microsoft.AspNetCore == 2.1.7 strategy: min`

I am leaving this here for reference.
