### ISSUE TITLE
MSBuild errors are not reported as errors to TeamCity

### ISSUE THREAD

**Issue by otto-gebb** [fsharp/FAKE#2252]
When a build breaks because of a compilation error, too much work needs to be done to discover the error reported by the compiler.

Looks like FAKE doesn't report compiler error messages as errors to TeamCity, although these messages are red in the log.

The image below illustrates what I mean.
![2019-02-14_22-44-27](https://user-images.githubusercontent.com/5798003/52820563-9c854a80-30ac-11e9-9cbe-e0237966a247.png)

When I filter the build log to show only "Important messages", I don't see compiler errors:
![2019-02-14_22-55-19](https://user-images.githubusercontent.com/5798003/52820661-d6eee780-30ac-11e9-9146-85cfd5bca211.png)

### Repro steps

1. Have a build in TeamCity broken because a C# file doesn't compile.
2. Open the build log.
3. Try to discover the root cause.
4. Suffer.

### Expected behavior

The compiler error message is recorded as an error, and you can quickly find out why the build is broken.

### Actual behavior

See screenshots above.

### Known workarounds

None.

### Related information 

* Don't know if related, but if I try to log anything in the FAKE script with `Trace.traceImportant`, the message doesn't appear in TeamCity build log.
* FAKE 5.12
* TeamCity Professional 2018.2.2 (build 61245)

**Comment by matthid** [comment]
Yes it looks a lot better on other CI systems. TeamCity is a special piece of pain for me because I already invested a lot of time (while not using it myself) to get it running with https://teamcity.jetbrains.com (which I'm glad that they provide free hosting). However, it seems to fail randomly when then build gets queued on random agents. For example look at the current build failure: https://github.com/fsharp/FAKE/pull/2234

![image](https://user-images.githubusercontent.com/1866463/52821312-baec4580-30ae-11e9-93ad-3624e80a39a5.png)

I think best would be if someone actually using the thing could help there actively as I'm probably not able to do it anymore.

To be completely honest I'm thinking about disabling TeamCity in this repository again (as I really don't like red builds).

**Comment by otto-gebb** [comment]
@BlythMeister as I remember, you have done something related to TeamCity recently. Maybe you could take a look at this?

**Comment by otto-gebb** [comment]
Fixed by #2258.
![image](https://user-images.githubusercontent.com/5798003/53731130-132a9200-3e7a-11e9-9e22-8746864c2398.png)
