### ISSUE TITLE
No way to force FAKE CLI tool to use ANSI coloured output on CI

### ISSUE THREAD

**Issue by TomaszG** [fsharp/FAKE#2270]
### Description

Can't find the way to force FAKE CLI tool to use ANSI coloured output on CI.

### Repro steps

1. Run some simple build.fsx file via CMD/powershell locally using `fake.exe run build.fsx` command
2. Run the same command but via Jenkins with ANSI colour support (e.g. via [AnsiColor plugin](https://plugins.jenkins.io/ansicolor)) or any other CI which supports colourised output
3. Compare outputs

### Expected behaviour

Outputs should be the same OR user should have a way to force the same behaviour on CI.

### Actual behaviour

The output from 1st step is colourised:
![Console output](https://i.imgur.com/LUh8Bnj.png)

The output from CI is not colourised:
![CI output](https://i.imgur.com/SXWaQZL.png)

### Observations

I tried to force color via setting `FORCE_COLOR=1` environment variable (like for yarn or npm) and by settings `BuildServer.ansiColorSupport <- true`, however, it helped only for subcommands executed by FAKE (i.e. yarn and dotnet/msbuild). Is there any way to force it for the fake CLI output too?

### Related information 

* Windows
* .NET Core 2.2
* Severity: medium
* FAKE 5.12.4

**Comment by matthid** [comment]
Indeed,
AppVeyor implementation for example uses 
https://github.com/fsharp/FAKE/blob/00d5bb2d3644c80314630591d66ed302d1b45032/src/app/Fake.BuildServer.AppVeyor/AppVeyor.fs#L287
Because that one always supports ANSI color. In TeamCity the implementation currently looks like this:
https://github.com/fsharp/FAKE/blob/00d5bb2d3644c80314630591d66ed302d1b45032/src/app/Fake.BuildServer.TeamCity/TeamCity.fs#L391

I guess the "fix" would either be to honor the `ansiColorSupport` in the Console writer in general or honor it in the TeamCity implementation.
