### ISSUE TITLE
Remainder: Set RollForward once we upgraded to .NET core 3.0

### ISSUE THREAD

**Issue by rusanov-vladimir** [fsharp/FAKE#2325]
I'm trying to run fake 5 script on ubuntu using latest .NET core 3 preview5.

I uninstalled previous SDK versions so it's the only .NET core version I got.
After installing global tool with `dotnet tool install fake-cli -g`
I'm getting error above:

>It was not possible to find any compatible framework version
>The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
>  - The following frameworks were found:
>      3.0.0-preview5-27626-15 at [/home/st/dotnet/shared/Microsoft.NETCore.App]
>
>You can resolve the problem by installing the specified framework and/or SDK.
>
>The .NET Core frameworks can be found at:
>  - https://aka.ms/dotnet-download

Seems to be similar to #1974.

Is there any reason why fake cannot run on dotnet core 3.0 preview?

**Comment by baronfel** [comment]
Until fake is published for 3.x, it's not going to run on it successfully. Global tools are runtime-dependent, not self-contained, and so running them requires a compatible runtime to be present on the system.  The runtime resolution rules can be found `[here](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#what-could-go-wrong)`, but the long and short of it is

* first check within the same major/minor for a compatible patch version
* if none found, look for a compatible minor version
* else fail


It looks like you're hitting the third case, because FAKE is compiled for 2.1, which means it works on 2.1 and 2.2 runtimes.

**Comment by matthid** [comment]
Well they introduced some roll-forward settings we "could" use:

https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#major-version-roll-forward

-> We could add `RollForward=Major` to the project file

**Comment by rusanov-vladimir** [comment]
Thanks for the answers! 
I was aware about runtime resolution rules, but it seemed too awkward that net core 3.0 is backward compatible with 2.x but I wasn't able to run fake with it. Using environment variables I'm able to run fake smoothly without installing older runtime. I think adding `RollForward=Major` to the project would be great to have this behavior out of box without the need of using environment variables.
Thanks again!

**Comment by matthid** [comment]
@rusanov-vladimir Thanks for confirming that this actually works ;)

**Comment by matthid** [comment]
Ok, I'm labeling this as "extern" because dotnet SDK 3 is not yet released. I'm no longer playing around with previews. However, I would probably accept a PR updating all the required places. Considering there is a workaround I'll leave this open as a reminder until SDK v3 has shipped. Please feel free to remind me about this issue when that happened :)

**Comment by matthid** [comment]
This should be solved in 5.16 due to https://github.com/fsharp/FAKE/pull/2372
