### ISSUE TITLE
FAKE for non-specialists?

### ISSUE THREAD

**Issue by charlesroddie** [fsharp/FAKE#2339]
Questions about FAKE from a beginner. I know F# very well and use Azure DevOps for builds and releases. But it's hard for me to work out what FAKE is despite having read the introductory docs. Thanks for any help and sorry for the long posting.

1. I like the idea of defining builds/releases/runs in F# code. This would give a lot of flexibility. Is that what FAKE does?

2. Is there any way to get access to the nice stuff in Azure DevOps? There are so many tasks defined there things very easy. Can these tasks be called from FAKE?

3. Installing FAKE. https://fake.build/fake-gettingstarted.html is not clear to me. I haven't used a command line for a couple of decades, and I think it's pretty important to us that FAKE is used from a project, which can therefore reference other projects. A script is going to be really tricky to get working. Can I just take a .Net F# project, install https://www.nuget.org/packages/FAKE/ and run it? Will that work?

4. The intro docs seem to require a lot of background knowledge. I don't understand most of the lines of code - this could just be because I need to work out how to install FAKE so I can see the intellisense. I gather that a target is a sequence of things to do, but defining sequences of things to do is easy in any programming language, so why do targets exist?

5. There are a lot of strings in the intro docs which looks like a code smell. For example targets are referenced by strings rather than as objects. I assume that this was done to avoid using the keyword `let` which might put off non-F#ers. There are also operators `==>`, `!!`, `++`, `--`. I have seen similar operators in other F# projects (testing, web routing) and in those projects they look nice at the cost of incomprehensibile type signatures. I don't want to introduce unnecessary strings and incomprehensible type signatures into our nicely typed codebase.

6. I think I would like to create an F# project with something like the code below. Then we could run this locally, or have a simple build command in AzureDevOps to run this project. Does FAKE enable any of this or am I looking for something very different?

```fsharp
build "..\Project\project.fsproj"
Yaml<AzureDevopsYamlFilenameLiteral>.Run()
let x = ModuleInSomeReferencedProject.SomeVariableDefinedInCode
runExe(filename = "..\Project\build\project.exe", input = x)
runProject(filename = "..\Project\project.fsproj", input = x)
````

**Comment by matthid** [comment]
Hey, yes we probably need to improve some of the introduction documents, thanks for the concrete pointers.

> I like the idea of defining builds/releases/runs in F# code. This would give a lot of flexibility. Is that what FAKE does?

Indeed. The scope is a bit larger, you can do any kind of automation. Build/Release is the most common scenario.

> Is there any way to get access to the nice stuff in Azure DevOps? There are so many tasks defined there things very easy. Can these tasks be called from FAKE?

We try to integrate nicely into existing build server features. This particular integration is not planned. I'm also not sure if it is a good idea (thought about it myself) considering how we want fake scripts to run locally as well...

> I think it's pretty important to us that FAKE is used from a project, which can therefore reference other projects. A script is going to be really tricky to get working. Can I just take a .Net F# project, install https://www.nuget.org/packages/FAKE/ and run it? Will that work?

Almost, you can indeed use a regular project, but it isn't documented very nicely, you will not get any features of the fake runtime, including the new fake tooling in Ionide ;)

You can use code similar to how you'd do it when using fsi instead of fake runtime, see https://fake.build/fake-debugging.html#Run-script-without-fake-exe-via-fsi

After that you can just add the nuget packages you need according to the docs. For example Fake.IO.FileSystem.

> this could just be because I need to work out how to install FAKE so I can see the intellisense. I gather that a target is a sequence of things to do, but defining sequences of things to do is easy in any programming language, so why do targets exist?

Yes tooling needs to improve further. Regarding targets: The idea is to resolve the dependencies between them and running them in the correct order or in parallel depending on what state of the build you need right at the moment.

> I don't want to introduce unnecessary strings and incomprehensible type signatures into our nicely typed codebase

Take a look at https://github.com/vbfox/FoxSharp/blob/master/src/BlackFox.Fake.BuildTask/Readme.md

> Does FAKE enable any of this or am I looking for something very different?

Well at least some of it, and it looks different ;)

Any idea how to improve the docs given the responses? Are there still open questions?

**Comment by matthid** [comment]
@charlesroddie I hope I addressed this in the recent documentation changes.
In particular, you can now click on the [`WHY USE FAKE?`](https://fake.build) question in the starting page which leads you to the [FAQ](https://fake.build/fake-what-is-fake.html). It answers some of your questions. Additionally, we had two "getting-starting" guides which now have been [consolidated into one](https://fake.build/fake-gettingstarted.html). This is now the "first contact" page if you decided you want to give FAKE a try.

As always suggestions and improvements are welcome. Thanks for the detailed write-up of the issues you were encountering.
