### ISSUE TITLE
MissingMethodException: FSharpChecker.Create()

### ISSUE THREAD

**Issue by cartermp** [fsharp/FAKE#2494]
### Description

I'm attempting to port and then re-enable the old tests in FsLexYacc. This is being done in the following branch: https://github.com/cartermp/FsLexYacc/tree/enable-old-tests

### Repro steps

In that repo, with that branch:

1. Run the build script
2. Run `dotnet fake -v run tests\fsyacc\OldFsYaccTests.fsx`

### Expected behavior

No `MissingMethodException`. Perhaps these tests aren't quite right, though.

### Actual behavior

`MissingMethodException`.

```
Script reported an error:
-> MissingMethodException: Method not found: 'FSharp.Compiler.SourceCodeServices.FSharpChecker FSharp.Compiler.SourceCodeServices.FSharpChecker.Create(Microsoft.FSharp.Core.FSharpOption`1<Int32>, Microsoft.FSharp.Core.FSha
rpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Resolver>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`2<System.String,Syste
m.DateTime>,Microsoft.FSharp.Core.FSharpOption`1<System.Tuple`3<System.Object,IntPtr,Int32>>>>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>)'.
   StackTrace:
        at Fake.DotNet.Fsc.scsCompile(String[] optsArr)
        at Fake.DotNet.Fsc.compileFiles(FSharpFunc`2 compiler, FSharpList`1 srcFiles, FSharpList`1 opts) in D:\a\1\s\src\app\Fake.DotNet.Fsc\Fsc.fs:line 343
        at Fake.DotNet.Fsc.doCompile(FSharpFunc`2 compiler, FSharpList`1 fscParams, FSharpList`1 inputFiles) in D:\a\1\s\src\app\Fake.DotNet.Fsc\Fsc.fs:line 352
        at Fake.DotNet.Fsc.compile(FSharpList`1 fscParams, FSharpList`1 inputFiles) in D:\a\1\s\src\app\Fake.DotNet.Fsc\Fsc.fs:line 419
        at Oldfsyacctests.fsc(String output, FSharpList`1 files) in C:\Users\phcart\source\repos\FsLexYacc\tests\fsyacc\oldfsyacctests.fsx:line 51
        at <StartupCode$oldfsyacctests_7B84D11B5F1B5F47658F2F4A3605C240D22967CF1FBF4A4592D8A1D6CBDB9C45>.$Oldfsyacctests$fsx.main@() in C:\Users\phcart\source\repos\FsLexYacc\tests\fsyacc\oldfsyacctests.fsx:line 148
```
The verbose log points at some assembly redirection for FSharp.Compiler.Service, could that be related?

### Known workarounds

None that I am aware of.

### Related information 

* Operating system - Windows
* .NET Runtime - .NET Core
* Version of FAKE - 5.x

**Comment by matthid** [comment]
> The verbose log points at some assembly redirection for FSharp.Compiler.Service, could that be related?

Yes very likely. Sadly FCS has the nasty property that you can never mix different versions in your dependency tree. 
Without further checking I'd assume that in your dependency tree of the script references multiple versions of it and the latest is taken by paket and Fake at runtime (which would be by design).

In contrast to pre fake 5 area the fake runtime itself shouldn't matter (Fake.Dotnet.Fsc is a 'normal' script dependency in this situation).

My bet would be that you updated some deps and either you have a different dependencies on FCS, then you need to make sure (manually) that all deps depend on the same version of FCS. Alternatively if you only depend on FCS via Fake.Dotnet.Fsc you might need to explicitly pin a compatible FCS version to prevent paket from taking a newer version.

Let me know if that helps.

**Comment by cartermp** [comment]
Thanks @matthid, that's probably it. I do depend on FCS transitively via FSharp.Formatting, so I'll try to get that sorted and report back.

**Comment by matthid** [comment]
Let me know if you need an update in Fake.Dotnet.Fsc - It is already in the pipe. Look out for the latest prereleases. I wanted to fix an issue in ionide first before releasing 5.20

**Comment by cartermp** [comment]
Update: I ended up not needing this at all, since it was simpler to just transition the calls to Fsc into proper projects and just build/run them. I highly suspect this is the dependency tree issue you mention and unrelated to this module, so I'll close this out.
