### ISSUE TITLE
How do I silence Fsc warnings when doing DotNet.publish?

### ISSUE THREAD

**Issue by retendo** [fsharp/FAKE#2504]
### Description

I want to silence warnings with a specific code when doing DotNet.publish. I thought I could suppress them by providing MSBuildParams with NoWarn = Some ["44"], but that doesn't work.

The output still says

> Fsc: somefile.fs(345,22): warning FS0044: This construct is deprecated. Some deprecation message

Is there a way to tell Fsc to ignore these warnings?

### Related information 

* macOS 10.15.2
* .NET Core
* Version of FAKE 5.18.2

**Comment by matthid** [comment]
Hey @retendo, can you please check the MSBuild command line (FAKE should print what it has started) manually?
- Check and report if this happens when you start the command line manually
- Check what the proper command line is (maybe you need to ask the MSBuild guys if it isn't properly documented or not working as expected).
- Once we have that info we can follow up here and see what we need to do in FAKE itself.
