### ISSUE TITLE
How to force fake to use 64 bit tools

### ISSUE THREAD

**Issue by MarkNicholls** [fsharp/FAKE#2546]
I'm compiling a large code base using a basic fake build script (not the total script).
The solution is dotnet core 2.2, developed in visual studio 2019 (no paket).

```
let configuration = "release"
let vsProjProps = [
     ("Platform", "Any CPU") 
     ("Configuration", configuration)
     //("PackageReleaseNotes", release.Notes |> List.head)
     ("VersionSuffix", "")
     ("VersionPrefix", "1.0." + buildNumber)
]

Target.create "BuildApp" (fun _ ->
  !! "./**/*.sln"
    |> MSBuild.runReleaseExt id "" vsProjProps  "build"
    |> Trace.logItems "AppBuild-Output: "

```
and it runs out of memory.

`(Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
Fsc: error FS0193(0,0): error : Exception of type 'System.OutOfMemoryException' was thrown.`

When I watch the processes (using task manager) I notice that "MSBuild.exe (32 bit)" is a child of the command prompt, and eventually "fsc (32 bit)" kicks in....and then blows up.

I suspect if I can force the build to use a 64 bit compiler, my memory issues would go away, but how do I do this?

**Comment by matthid** [comment]
It looks like this can be reproduced without FAKE on the commandline. So please try to run the command standalone and if you can reproduce the best bet is to report this in the compiler directly.

**Comment by MarkNicholls** [comment]
its no surprise that the 32 bit compiler runs out of memory, the question is really how does FAKE decide which of the multitude of build tools microsoft has littered my machine with, to use, and how can I suggest it picks a 64 bit one.
If I type msbuild on a vanilla command line, it will say "not found".
Sorry...I'm a bit of a noob.

**Comment by matthid** [comment]
> The solution is dotnet core 2.2

Before reading the rest of this answer: The problem might be that you run msbuild and you probably want to run the .Net SDK instead (ie `dotnet build` instead of `msbuild`). Maybe that already fixes the problem, see https://fake.build/dotnet-cli.html

> its no surprise that the 32 bit compiler runs out of memory

I wouldn't say that. I'd still check what the experience is with Visual Studio, the dotnet sdk on the command line or rider. I wouldn't be surprised if it fails there as well.

> the question is really how does FAKE decide which of the multitude of build tools microsoft

Still, we first would need to see if there is even a way outside of FAKE which works. If there isn't than there isn't a way with FAKE obviously (as FAKE is just running the existing tools)

> If I type msbuild on a vanilla command line, it will say "not found".

Fake usually prints the full command line of the processes it starts including full path of the executable and it's arguments. It should work to just execute the same in a regular command prompt. You might need to remove some logging arguments (which is a bit specific for FAKE to get the output of the executed msbuild command). You can paste the FAKE output if you have trouble finding a working command line command. If it isn't obvious you also need to `cd` into the project directory first.

**Comment by MarkNicholls** [comment]
ah yes of course sorry...I was interpreting msbuild as msbuild.exe, not through the dotnet cli.
I have tried to get VS to use the 64 bit version, but that's another world of pain.
I can see that fake goes to the "current" msbuild, and this (for some reason that only ms knows) is a 32 bit one.
Believe me, it is no surprise the 32bit version chokes, I'm literally compiling thousands of type definitions.

I'll have a go via dotnet msbuild, and see what happens

**Comment by matthid** [comment]
Just to clarify: If you can't compile it even on the command line you shouldn't try to make it work with FAKE. You should first try to get it working on the command line and then try to run that from FAKE (or feel free to ask how to run that particular command line to ask if you have trouble implementing it)

And if you can't compile if on the command line you should ask the compiler guys ;)

**Comment by MarkNicholls** [comment]
fair enough.
I've tried to compile it 3 ways, and each way it blows up (32 bit msbuild, 64 bit msbuild, dotnet build).
so lets close this
