### ISSUE TITLE
Fake namespace isn't visible

### ISSUE THREAD

**Issue by atsapura** [fsharp/FAKE#2569]
### Description

Compiler throws an error `The namespace or module 'Fake' can not be found`

### Repro steps

- Create F# console app (netcoreapp3.1 or net5.0)
- Add `Fake` nuget package (v. 5.16.0 as of today)
- `open Fake`

### Expected behavior

namespace is found, functions are available

### Actual behavior

compile error

**Comment by yazeedobaid** [comment]
Thanks, @atsapura for reporting the issue! Fake v5.16.0 is considered a legacy. Please use the new FAKE modules.
I tried the steps you mentioned and used `Fake.Core.Target` v5.20.4 instead of the legacy package and it provided the autocompletion and it builds and ran successfully.
Please note that to use FAKE outside of a script you need to set its execution context. The following is a sample entry point for a console app that uses `Fake.Core.Target` and it set execution context:

```
open System
open Fake.Core

[<EntryPoint>]
let main argv =
    // set FAKE execution context
    let execContext = Context.FakeExecutionContext.Create false "build.fsx" [ ]
    Context.setExecutionContext (Context.RuntimeContext.Fake execContext)

    Target.create "Hello" (fun _ -> 
        printfn "Hello!"
    )
    
    Target.runOrDefault "Hello"
    0
```
