### ISSUE TITLE
FAKE for Continuous Delivery

### ISSUE THREAD

**Issue by panesofglass** [fsharp/FAKE#282]
a la [Jez Humble's book](http://www.amazon.com/Continuous-Delivery-Deployment-Automation-Addison-Wesley/dp/0321601912)

I think this may already be possible. This could simply be a documentation task. By continuous delivery, I'm thinking of something like the following:

1. Commit stage: Run CI build including compile, unit tests, and publish artifacts
2. If successful, kick off test stage
3. Test stage: Retrieve artifacts from drop folder, run acceptance tests
4. If successful, allow manual or automated navigation to next stage(s), e.g. UAT or Production

Obviously, different people will want different stages. I think the current use of FAKE is to go from Commit to "Production" via NuGet (in most projects).

Further thoughts:

* Fake.Boot seems to do part of this in that it separates a Fake build into two stages for the benefit of pulling initial dependencies.
* Fake.Deploy provides deployments, but what if I want to kick off a automated tests? How would that work?
* Does FAKE already include a mechanism to ask for manual intervention? I'm not married to the idea that this belongs in the script. I could easily build a tool that looked at deployed versions and allowed you to "push a button" that would pass the appropriate parameter to a FAKE deploy script.

**Comment by nathanaeljones** [comment]
I've used Fake to update `paket.dependencies` and `packet.references`, follwed by `paket update --redirects --force` on a second Git repo, triggering testing and deployment of libraries into staging server applications. 


### Some friction using FAKE w/ CI: 

1. Using the build number from CI isn't documented.  APPVEYOR_BUILD_NUMBER and TRAVIS_BUILD_NUMBER provide sequential values, which is very handy when you publish every successful commit to a nuget feed as an incrementing prerelease. Unique build numbers are handy (If not in CI, I use (`DateTime.UtcNow.TimeOfDay.Milliseconds % int Int16.MaxValue`))  Build metadata would be nice to, as it could help identify release (non-prereleases) versions as well. 
2. Git SHA1 values don't seem to be automatically added to assemblyinformationalversion.  On CI, this is available via env vars. 
3. Version number sourcing. There are 4 places it's stored - AssemblyInfo (which is used by Visual Studio), Release Notes (used by Fake), appveyor.yml, and git tags.  Some users hang out in VS/TestDriven.NET, and Fake only runs on CI; others use Fake and $EDITOR, but don't open VS. Divergent values seem inescapable unless the build fails if they're mismatched.


### Public releases hold a few more issues: 

Some projects are quite large, and a release involves uploading hundreds of megabytes. Maintainers personal internet connections may not be reliable enough to complete the task, but a CI server can. Streamlining public releases via CI is important. The clearest way to detect a 'release' is by parsing the git tag. When a commit is tagged, the CI server gets a notification, and runs FAKE with an extra environment variables (APPVEYOR_REPO_TAG_NAME, TRAVIS_TAG, etc). Transient errors can be fixed by re-running the build from the CI interface. 

On public CI servers, nuget/github tokens can be encrypted and stored in the repository. These tokens can be compromised by any user with push access - but there will be a clear trail to the user. CI services could improve security by decrypting certain credentials only for signed commits. 

Fake scripts which deal with all of these real-world complications can be hard to manage. It would be great to see examples or scaffolding that deals with credential management, git tags, multiple publish feeds, etc. on and off CI.

**Comment by panesofglass** [comment]
I'm going to close this, as we have found other ways around the problem using PowerShell.
