### ISSUE TITLE
System.Exception is reported to Teamcity on failing NUnit tests

### ISSUE THREAD

**Issue by brase** [fsharp/FAKE#658]
Fake is reporting an exception to teamcity when some of my nunit tests fail:
![nunit-teamcit-fake](https://cloud.githubusercontent.com/assets/170088/6284664/e3877146-b8f2-11e4-98e7-560cc962e612.png)

The consequence of this is that teamcity is showing an ugly exception for build configurations with failing tests:
![nunit-teamcit-fake2](https://cloud.githubusercontent.com/assets/170088/6284674/ff95273e-b8f2-11e4-996a-1cd760fdfd7d.png)

Instead of this exception I expectod to see something like this:
![nunit-teamcit-fake3](https://cloud.githubusercontent.com/assets/170088/6284678/0efb4992-b8f3-11e4-9c80-7376978d96d4.png)

Any idea how I can achieve this?

**Comment by forki** [comment]
the issue is that we let the build fail by raising an exception (needed for local builds and other build servers).

As you said we already reported the test errors to TC, but the generic build failure in https://github.com/fsharp/FAKE/blob/master/src/app/FAKE/Program.fs#L153 is reporting the exception.

Somehow we would need to special case this.

**Comment by brase** [comment]
Maybe it should be a typed exception instead.
This type of exception then should not be reported to teamcity.

**Comment by forki** [comment]
yes that sounds like a good solution. Would love to see a PR.

2015-02-20 12:56 GMT+01:00 Sebastian Brandt <notifications@github.com>:

**Comment by brase** [comment]
This one can be closed, right?
