### ISSUE TITLE
3.25.2 is not working

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#710]
Please build a new package or roll back.

Error:
Downloading latest version of NuGet.exe...
Downloading latest version of Fake.exe...
Unable to find version '3.25.2' of package 'FAKE'.
The system cannot find the path specified.

**Comment by forki** [comment]
do you have any details? What's wrong with the package?

**Comment by mynkow** [comment]
Unable to find version '3.25.2' of package 'FAKE'. We cannot update from nuget to this version

**Comment by forki** [comment]
that's a nuget bug. they still didn't fix their eventual consistency bug and probably never will.

/cc @csharpfritz @maartenba

**Comment by forki** [comment]
(You have to wait until the servers synchronized. The issue is that the service which shows all available versions is faster than the download server)

**Comment by forki** [comment]
does it work now?

**Comment by mynkow** [comment]
yes, I guess we should consider staying on a specific version instead of downloading the newest because right now production deployments are failing.

**Comment by forki** [comment]
so you can confirm, that this is the eventual consistency bug?

**Comment by mynkow** [comment]
Yes, I confirm. Production is green now

**Comment by forki** [comment]
It's super sad, but I can only recommend to pin to a concrete version.

**Comment by raymens** [comment]
Had the same issue some time ago, this should really be fixed by the Nuget team ASAP

**Comment by yishaigalatzer** [comment]
Thanks for the feedback. @Jeffhandley is no longer working on nuget, please use my name instead. We are discussing this at the moment and see if we can come up with a way to fix it.

We are trying to find out how exactly are you trying to get the latest, can you please provide the exact steps here? If you are trying to predict the url because it was just published the package, we don't expect this to work. But if you are hitting an end point to figure out latest and failing to install we would like to know and fix that.

Thanks!

**Comment by forki** [comment]
@yishaigalatzer thanks for responding here. I really appreciate that.

The repro is not really trivial, but this is what we know (seen over 100 times...):

* release a new nuget package version
* run "nuget.exe install" immediately after nuget push
* it fails to install on some machines (I assume depending on which server the load balancer gives you!? or some caching? but not on all machines)

The install process consists of 3 major parts:
  1) determine which version we want to install
  2) download that version
  3) run the install process

Since we don't specify a version, nuget.exe will assume "latest". So it asks the service for 1) and returns the latest.
Now in 2) it tries to download that concrete version. This step fails, since the download server doesn't have the version available.

After a couple of minutes (maybe 15) the same "nuget install" works on all machines.

**Comment by yishaigalatzer** [comment]
Thanks for the quick response. 

Specifically is it: `nuget.exe install Fake` ?

**Comment by forki** [comment]
Nope. I've seen this with other packages too
But FAKE is special since we release A LOT and people try to use "latest" in CI. And so things break.

Other projects don't really report this. If you install Newtonsoft.Json then you pin it to a specific version and everything works. If you are unfortunate and try to install it just a minute after @JamesNK did the release then you probably just curse VS and try again later.

**Comment by yishaigalatzer** [comment]
Thanks @forki I think we know what is going on, and we discussed a possible solution. Can't promise when we start actually working on it as we have some other deliverables that come first.

I'm hoping that we can make progress within a week or two, but like I said above we will have to wait a bit and see.

**Comment by forki** [comment]
I'm already  waiting for for this for a couple of years. So no worries. I'm pretty happy that finally someone is trying to understand the issue. ;-)

**Comment by mynkow** [comment]
https://github.com/NuGet/Home/issues/268
