### ISSUE TITLE
Failing NUnit tests in v4.0.2

### ISSUE THREAD

**Issue by DigitalFlow** [fsharp/FAKE#896]
Hello everyone,

we are experiencing errors when running NUnit from FAKE v4.0.2.
In our tests we are trying to get some connection strings from app.config, which fails when tests are being run by FAKE. The app.config is correctly copied to the test directory and it contains the connection string that we want.
.NET Version is 4.5.
The issues don't appear, when running the tests directly in NUnit Runner or when version 3.36.0 of FAKE is being used.

Since version 3.36.0, two pull requests targeted NUnit:
https://github.com/fsharp/FAKE/pull/870
https://github.com/fsharp/FAKE/pull/883

It might be, that one of them broke something in NUnit.
Running FAKE with cache disabled ("-nc") or setting domain via adding 

`Domain = NUnitDomainModel.DefaultDomainModel`

in test target did not resolve the issue either.

Kind regards,
DigitalFlow

**Comment by andersosthus** [comment]
PR #870 targets XUnit2.fs, and only affects tests run with XUnit.

Could you test with FAKE 4.0.1? This one was released before #883 was added, so we could narrow it down a bit.

**Comment by DigitalFlow** [comment]
Just tested it with version 4.0.1 of FAKE.
This behaviour is not present there, so version 4.0.1 was fine.

**Comment by andersosthus** [comment]
So that narrows it down to either #883 or #884 then, right ?
Does it fail with any sensible error message ?

**Comment by andersosthus** [comment]
But that should be the default according to this:
https://github.com/fsharp/FAKE/blob/e0345e7a1e52f58f326561d4afe99ce7d7b287b6/src/app/FakeLib/UnitTest/NUnit/Common.fs#L139

**Comment by DigitalFlow** [comment]
Correct, this is why I'm wondering about the issue.

**Comment by DigitalFlow** [comment]
02

**Comment by forki** [comment]
Weird

**Comment by DigitalFlow** [comment]
I'm currently looking into it.

**Comment by DigitalFlow** [comment]
Ok sorry, I just double checked and it seems as if NuGet had problems replacing v 4.0.1 (that I deployed manually) with v 4.0.2, so it stated that it installed v 4.0.2, but v 4.0.1 was still ran.
I tested it again and setting domain to either DefaultDomainModel or SingleDomainModel both have no effect on this issue.
With v 4.0.2, NUnit it is still failing.
The exception is thrown by our own code, if the ConfigurationManager could not load our connection strings.
As I said though, the app.config is copied to the test directory and the connection string is present.
Since Resharper runs those tests successful and even the NUnit Runner, the problem must be within FAKE.

**Comment by andersosthus** [comment]
Ok, so this is my take on it:

Before #833 the default in NUnit.fs was to not pass and domain flag to NUnit runner: https://github.com/TheAngryByrd/FAKE/blob/5716dd3e4d09ec50611454971f428aedca1f957b/src/app/FakeLib/UnitTest/NUnit/Common.fs#L34, https://github.com/TheAngryByrd/FAKE/blob/5716dd3e4d09ec50611454971f428aedca1f957b/src/app/FakeLib/UnitTest/NUnit/Common.fs#L139, https://github.com/TheAngryByrd/FAKE/blob/5716dd3e4d09ec50611454971f428aedca1f957b/src/app/FakeLib/UnitTest/NUnit/Common.fs#L161

According to the NUnit documentation, this lets NUnit decide. If you specify a single test assembly, it should run in Single, and if you specify multiple, is should use multiple domains (http://www.nunit.org/index.php?p=consoleCommandLine&r=2.5 - almost at the end).

After #833 the default is "Single":
https://github.com/fsharp/FAKE/blob/e0345e7a1e52f58f326561d4afe99ce7d7b287b6/src/app/FakeLib/UnitTest/NUnit/Common.fs#L35, https://github.com/fsharp/FAKE/blob/e0345e7a1e52f58f326561d4afe99ce7d7b287b6/src/app/FakeLib/UnitTest/NUnit/Common.fs#L139,
https://github.com/fsharp/FAKE/blob/e0345e7a1e52f58f326561d4afe99ce7d7b287b6/src/app/FakeLib/UnitTest/NUnit/Common.fs#L161

Notice on Line 161, it will now pass ```-domain:Single``` by default, and no matter what you change it to, it will always include ```-domain:VALUE```, unlike the previous version where it wouldn't pass the ```-domain``` flag by default (it was ```String.Empty```), since none of the values are ```String.Empty```.

Are you running multiple assemblies at once ? If so, if you want the behaviour to be the same as before (when NUnit determined this itself), you need to pass ```Domain = MultipleDomainModel```.

If not, I'm not sure.

**Comment by forki** [comment]
I'd really appreciate a PR. I'd merge/release it asap.

**Comment by andersosthus** [comment]
I'll make a PR and send to you, but I would like to know if setting ```Domain = MultipleDomainModel``` fixes @DigitalFlow issue, so that we can be sure :)

**Comment by DigitalFlow** [comment]
Just verified it: Setting
`Domain = MultipleDomainModel`
in unit test target makes the build pass successfully.

**Comment by andersosthus** [comment]
Great @DigitalFlow :)

I'll create a PR for you @forki

**Comment by andersosthus** [comment]
With the release of 4.1.0 this can probably be closed now ?
